### ISSUE TITLE
Allow selection of Material Attributes to export

### ISSUE THREAD

**Issue by der-On** [der-On/XPlane2Blender#125]
This is important to increase drawing performance in the simulator.

The less Material Attributes, the better the performance. X-Plane's default fit well for Textured materials without tinting.

**Comment by tngreene** [comment]
Was this optimization ever completed?

**Comment by bsupnik** [comment]
No, and it's not clear to me that this is actually how we want to solve this problem.
The problem is that users sometimes get 'random' material values in their materials and the exporter takes them seriously.

We solved this problem for specularity via the normal-metalness directive.

At this point I am undecided on the way to proceed, but I can say this is _not_ a 3.4 feature.

**Comment by tngreene** [comment]
This is a very general bug report and I think not very useful. We don't want "Less unneeded material textures", we want "No unneeded material attributes! (To the best of our ability to tell with the information and specs we have)". That isn't a bug to solve, that's an overall design goal of the exporter.

#366 goes a long way to solves this, #368 is working on this. Closed for being too vague.
