### ISSUE TITLE
Animation rewrite

### ISSUE THREAD

**Issue by der-On** [der-On/XPlane2Blender#131]
See [Wikipage](https://github.com/der-On/XPlane2Blender/wiki/Design-of-the-New-Animation-Export-Code) for reference.

**Comment by der-On** [comment]
@bensupnik I was thinking of simply resuing the XPlaneObject type instead of creating another XPlaneBone type and then move writing of export code into XPlaneObject instead.

XPlaneObjects already store hierarchy that matches the hierarchy of the objects in blender.

**Comment by bsupnik** [comment]
Hi Ondrej,

I think the bone needs to be _either_ its own class or a new derivative 
of XPlaneObject, because it can do things that make no sense for "all 
x-plane objects."

- Objects can export themselves, but bones can "open" and "close" their 
animation frame.
- Exportable entity objects can have LOD, attributes, wight.
- Bones have animation key frames, etc.

So I think you need to create a new class to isolate the new 
animation-specific code cases and not let them leak up into the base 
class; they're not something that -every- x-plane object should have.

My personal view is that deriving the bone from XPlaneObject isn't 
particularly valuable ... you pick up a ton of inherited stuff that you 
don't need, and the only "reuse" you get is that you have a source 
blender data block and a parent.


On 6/11/15 6:14 AM, Ondrej Brinkel wrote:
> @bensupnik I was thinking of simply resuing the XPlaneObject type
> instead of creating another XPlaneBone type and then move writing of
> export code into XPlaneObject instead.
>
> XPlaneObjects already store hierarchy that matches the hierarchy of the
> objects in blender.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/der-On/XPlane2Blender/issues/131#issuecomment-111077112>.
>

-- 
Scenery Home Page: http://scenery.x-plane.com/
Scenery blog: http://www.x-plane.com/blog/
Plugin SDK: http://www.xsquawkbox.net/xpsdk/
X-Plane Wiki: http://wiki.x-plane.com/
Scenery mailing list: x-plane-scenery@yahoogroups.com
Developer mailing list: x-plane-dev@yahoogroups.com

**Comment by der-On** [comment]
I'll put our conversation here for reference:

> **bsupnik:**  
> for what it's worth if there's a hierarchy of the exportable entities
> we can ignore  it and then cut it out when it's not used
> the important links are (1) every entity to its parent bone and (2) the bones to each other
> a not insane way to get there is:
> 1. bulid the new bone class
> 2. build code to collect them and to link entities to them
> at this point you've changed and deleted nothing
> then just go and dump the whole thing to console in python and make sure we have what we want
>  once you have a new bone skeleton
> with objects attached
> you can write the routines to get the bake matrices
> and the animation "prefix" for the bones
> (the animation prefix is basically the
> ```
> ANIM_begin
>     ANIM_translate bla bla bla bal bla
>    ANIM_rotate bla bla bla bla
> ```
>  that is needed to be "attached" to a given bone

**Comment by der-On** [comment]
Summed up from todays conversation:

- Each Blender Object or Blender Bone becomes an XPlane-Bone. There will be no premature bone-tree optimization, but the XPlane-Bone structue will represent exactly the bone + object hierarchy in blender.
- Each XPlane Bone will have 3 matrices: The Pre-Animation matrix, the post-animation matrix and a bake matrix
- The bake matrix is the matrix the objects vertices are transformed with in the "rest" position (without any animation applied)
