### ISSUE TITLE
Autodetect textures for OBJ file

### ISSUE THREAD

**Issue by der-On** [der-On/XPlane2Blender#137]
Make this feature optional to support both workflows.

1. [x] add option to autodetect textures based on first textures found in material(s)
2. [x] before export check each exported material if it contains the same textures, if not display a warning with incorrect materials
3. [ ] ~~only export if no texture errors have been found.~~ export anyway

**Comment by BlueishGhost** [comment]
Make things export anyways because its really difficult to spend all this
time on something just to have no returned results.

**Comment by der-On** [comment]
Okay. I'll just export it then and display the errors. No problem. I also have fallbacks for non-uvs that will set uvs to 0, 0.

**Comment by BlueishGhost** [comment]
Sounds good to me. Actaully, if X-plane just fails to load it anyway,
what's the use having it export. I don't know if it will fail.

**Comment by bsupnik** [comment]
"Make things export anyways because its really difficult to spend all this
time on something just to have no returned results."

This does not make sense to me. The returned results you need in the event of an export failure is instructions from Blender on how to fix the problem, not an OBJ that is _vaguely_ like what you authored but not actually like what you authored.  What is the use case where having the OBJ is useful when the Blender composition -cannot- be represented in X-Plane?

**Comment by BlueishGhost** [comment]
That's what I realized.

**Comment by der-On** [comment]
The resulting OBJ file will not be unloadable, but will propably not look as the author expects it.

The general problem is that in Blender there is currently no good way to display a dialog to the user.
I can only display short messages that will hide fairly quickly. So I think the best would be to create an internal text file with information about problems and solutions and reference to that text file in the error message or if possible display this text-file in a new blender window. I'll investigate.

**Comment by BlueishGhost** [comment]
Yes that would be good. "Error 22 look in Errors.txt for info..."

**Comment by der-On** [comment]
Implemented.

Things get logged as warnings now. If there are warnings or errors a dialog appears saying to look into the internal text file.
