### ISSUE TITLE
Support axis-angle and quaternion rotations

### ISSUE THREAD

**Issue by der-On** [der-On/XPlane2Blender#142]
Problem: If creating keyframes and rotating within the viewport, blender tends to create different axis for each keyframe for quaternions and axis-angle rotations.

**Comment by bsupnik** [comment]
First, why this happens: each key frame is a fully independent "pose" - that is, a rotation from the origin coordinate system to...something.  Each key frame is -not- stored relative to its previous key frame.

Therefore:
1. When the pose is at rest (no angle) the axis can be -anything- - and that choice is arbitrary.  Looks like 0,0,1 is the default.  So we can have a 'random' rest pose axis conflict with the 'real' actual pose angle.

This first case can be fixed by setting the axis to match its neighbors when the angle is 0.

2. When Eulers are composed, the axis goes nutty.  After that, trivial Euler changes cause pretty catastrophic angle changes.

This case -might- sometimes be fixable for two key frames by transforming both key frames by an arbitrary static rotation, such that the resulting rotation _between_ key frames is constant-axis.  The static transformation could then be merged with the static rotation.  Note that if there is a dynamic translation, this would have to be translated too!  Yikes.

Of coarse, there might simply be multiple arbitrary-angle rotations.  in this case the only real solution is to decompose into multiple animations (or change X-Plane).

TODO: find out what the typical interpolation mode is for bones.

**Comment by bsupnik** [comment]
From talking to Alex:
-Blender 2.49 appears to -only- support quaternion interpolation of pose bones.
-Jonathan's exporter will only export a quaternion correctly when there is only one axis for all non-zero rotations.

Therefore we can probably:
1. Convert all quaternions to axis-angle.
2. For all axis-angle, correctly 'fix' the axis when
2a. The angle is 0 - pick another axis that someone else is using and
2b. The axis is opposite direction - the axis and angle can both be reversed.

Ondrej: if you can create a function that takes an axis-angle key frame table and "fixes" it (or returns some kind of failure for un-exportable) I can try to implement something equivalent to Jonathan's logic.

**Comment by BlueishGhost** [comment]
Will the exporter export the same thing as blender 2.49 without having to
implement such non-quarternion rotations? Seems like it at least worked
well enough to create something visible that appeared to work.

**Comment by bsupnik** [comment]
Our expectation is that a Blender model from 2.49, once imported and forward converted using a one-time script, will export the same as 2.49, assuming quaternion-interpolated pose bones from 2.49.

In this particular case, I don't think the forward conversion script will do anything - we will be able to export the composition directly.

**Comment by BlueishGhost** [comment]
Are the bones and keys different now than from 2.49? Or do you use the same
procedures?

**Comment by bsupnik** [comment]
The _already shipping_ 2.70 exporter does not work the same as 2.49.
When we are done with this animation upgrade, 2.70's capabilities will be a -superset- of 2.49, so you will have the option of:
- Bones with quaternion interpolation
- Directly animate the data block's transform with any interpolation: quaternion, euler, etc.

It will not be legal to use a quaternion interpolation with 3 or more key frames where the axis of rotation is not consistent.  This case (inconsistent) axis causes problems in the existing 2.49 exporter, so there is no "unsupported" case in the new exporter that is supported in the old one.

**Comment by bsupnik** [comment]
The math for converting a quaternion to axis-angle:

http://www.euclideanspace.com/maths/geometry/rotations/conversions/quaternionToAngle/

angle = 2 * acos(qw)
x = qx / sqrt(1-qw*qw)
y = qy / sqrt(1-qw*qw)
z = qz / sqrt(1-qw*qw)

Special cases:
First normalize the quaternion, such that qw is not negative and not more than 1 (that is, is in [0..1]).
If qw is 1 then we have a singularity, but this is also angle = 0, so ... use angle = 0, axis = 0,0,1.  The axis is arbitrary - since there is no rotation.  We can "fix" angle mismatches later - see the next comment.

Otherwise, simply plug in this equation to get the axis angle from above.  When done, normalize x,y,z for X-Plane.  (Note: is the axis already normalized?)

**Comment by bsupnik** [comment]
Dealing with axis-angle mismatches:

Set our reference axis to undefined.
# Find the common axis of all key frames
For each key frame:
  If rotation angle is 0, 
    continue
  else
    if the reference axis is undefined
        set reference axis = this keyframe's axis
  else if the reference is equal to this axis
      continue
  else if the reference axis is opposite this axis
      invert axis and direction of this keyframe
  else
      error failure: we have at least two conflicting axes in a single key frame table - throw
# Handle degenerate case
if reference axis is still none:
    reference axis = 0,0,1    # note: in this case maybe we could have optimized out the rotate?!?
# go back and make everything consistent
for each key frame
    set the axis to the reference axis

**Comment by der-On** [comment]
@bsupnik awesome. Will implement asap.

**Comment by der-On** [comment]
I think we need to do the following to make axis angle work:

find keyframe pairs where the axis changes. Inject 3rd keyframe between them which has axis or second keyframe

special case is initial and second keyframe:

if the initial keyframe and the next have differing axis first keyframe should have axis of second keyframe (this is basically just an optimization of the injecting case)

**Comment by bsupnik** [comment]
Hi Ondrej,

I do not agree with this.

If -after the algorithm above- every key frame uses the same axis, we don't need to split anything - we can just write out the table.

If after the algorithm above the axes do not match, then _no_ amount of key frame injection is going to solve the problem, because the rotation is not one that can be represented with a single axis-angle key-frame animation in X-Plane.

Two key frames isn't the special case - "all the same axis" is the special case.

Let's not get into building multiple animations out of a single weirdly-key-framed axis animation unless we get strong test data that shows this is needed.

**Comment by der-On** [comment]
But actually even in the simple test cases we have now, axis are different in each keyframe. Do we need some kind of conversion into our common axis?

**Comment by bsupnik** [comment]
Uh oh..that's pretty worrying.  What's the test case name?

**Comment by der-On** [comment]
An example: `tests/animation/TestCase4.blend` -> layer 11

**Comment by der-On** [comment]
@bsupnik Please comment on this.

**Comment by bsupnik** [comment]
Who made this test case?  This looks like it should clearly be some kind of Euler but was converted to axis-angle representation?  This isn't the kind of rotation you'd get off of a bone.
