### ISSUE TITLE
Rename XPlaneLayer to XPlaneRoot

### ISSUE THREAD

**Issue by der-On** [der-On/XPlane2Blender#143]
## v3.3

`XPlaneLayer` will be renamed to `XPlaneRoot` but
`scene.xplane.layers` must still exist. The updater will move everything into `scene.xplane.roots`.
## v3.4

`scene.xplane.layers` will be dropped.

**Comment by tngreene** [comment]
I'm not convinced of the name change at all. XPlaneLayers isn't a perfect name, but updating the code base and creating a break in the data model is too big a risk for something so trivial. The ambiguity or confusion would be better taken care of by a comment that can be written in 20 seconds rather than 20 hours of testing and headaches.
