### ISSUE TITLE
LocRot, Loc, Rot directives on animated objects all export identically

### ISSUE THREAD

**Issue by danklaue** [der-On/XPlane2Blender#240]
These settings:

<img width="496" alt="screen shot 2017-04-19 at 3 28 22 pm" src="https://cloud.githubusercontent.com/assets/359923/25200695/e189beae-2514-11e7-80e9-2883b6e69b01.png">
<img width="498" alt="screen shot 2017-04-19 at 3 28 14 pm" src="https://cloud.githubusercontent.com/assets/359923/25200697/e1a4d342-2514-11e7-8354-f7bce23795eb.png">
<img width="502" alt="screen shot 2017-04-19 at 3 27 58 pm" src="https://cloud.githubusercontent.com/assets/359923/25200696/e1a30a12-2514-11e7-9779-59ce5fe89c37.png">

All produce the same result:

ANIM_begin
# translation keyframes
ANIM_trans_begin	carenado/g1000/atp/heading
ANIM_trans_key	0	-0.38352901	0.369663	-0.38486499
ANIM_trans_key	1	-0.38352901	0.369663	-0.38486499
ANIM_trans_end
# rotation keyframes
ANIM_rotate_begin	0	0	-1	carenado/g1000/atp/heading
ANIM_rotate_key	0	0
ANIM_rotate_key	1	3.99999997
ANIM_rotate_end
ANIM_hide	142	143	thranda/sim_scroll_hover
ANIM_show	0	0	thranda/panels/scrollWh

There's a need to assign ONLY rotation to knobs, because sometimes they'll cause rotating objects to "drift" over time, due to floating point rounding errors.

**Comment by tngreene** [comment]
This happens because... they don't do anything! Literally, that directive hasn't been used in the code base for a long long time. The UI was never removed and nobody realized it for > 2 years. The hope is that during the optimization, it will automatically select which keyframe types it should export.

For object you have animated there: What are its transformation properties at each keyframe? Do you have keyframes in location channels (just asking for thoroughness sake)?

-0.38352901 seems to be too big of a number to be a rounding error

**Comment by danklaue** [comment]
No, I do not have keyframes in location channels.

**Comment by bsupnik** [comment]
The resolution of this bug is that it should not be necessary for artists to hand-remove animations with this popup; X-plane should auto-optimize for WYSIWYG behavior.
