### ISSUE TITLE
Root Object not required to be empty. Is this correct?

### ISSUE THREAD

**Issue by tngreene** [der-On/XPlane2Blender#275]
I was always under the impression that one of the parts of being a root object was that it was an Empty data mesh. Is this really not actually required?

**Comment by tngreene** [comment]
In addition, if you click on a child object, surely it should disable the checkbox for being a root object. Right?

**Comment by bsupnik** [comment]
@alxunru Do we allow mesh-data blocks as the "OBJ" in Blender 2.49?  I think it might be moot because we use a two-level schema, so the geometry in a 'root mesh' would be lost.

@tngreene marking as high prio - let's be sure we know what we want before we release this and have to live with it forever.

@tngreene for disabling the child datablock's "root" check-box: yes, _ideally_ the child blender data block's "root" check-box should be disabled.

In practice, please don't do this if it's going to be a land war in Asia.  It seems like a use case fraught with edge cases, e.g. if you use Blender parenting to put a root object inside a root object, how can we cope with this sanely?

**Comment by tngreene** [comment]
That checkbox property, isExportableRoot is used very dumbly.

See xplane_file.py, 91-99

```python
def createFilesFromBlenderRootObjects(scene):
    xplaneFiles = []

    for blenderObject in scene.objects:
        if blenderObject.xplane.isExportableRoot and blenderObject.xplane.layer.export:
            xplaneFile = createFileFromBlenderRootObject(blenderObject)

            if xplaneFile:
                xplaneFiles.append(xplaneFile)

    return xplaneFiles
```

**Comment by tngreene** [comment]
So, I made an .blend file like this

```
Cube (root object)
|___Cube.001 (Root Object)
|     |___Cube.002 (Non-Root Object)
|___Cube.003 (Root Object)
|     |___Cube.004 (Root Object)
|___Cube.005 (Non-Root Object)
      |____Cube.006 (Root Object)
```

- Cube.obj will draw the vertices of Cube, Cube.001, Cube.002, Cube.003, Cube.004, Cube.005, and Cube.006
- Cube.001.obj will draw Cube.001, Cube.002
- Cube.003.obj will draw Cube.003, Cube.004
- Cube.004.obj will draw Cube.004
- Cube.006.obj will draw Cube.006

Predictably, there is no Cube.002 or Cube.005

**Comment by tngreene** [comment]
What are the chances this is currently getting abused?

**Comment by tngreene** [comment]
Definite changes
- Ban nested root objects, needs an export validation
- Allow non-empty as root object

**Comment by tngreene** [comment]
Does no nested root objects include

```
Cube (Non-Root)
|___Cube.001 (Root)
```
?

**Comment by bsupnik** [comment]
Ah - good question.  I would say that that is a LEGAL (albeit silly) configuration...the goal is to avoid nested roots, but as a general rule, roots don't examine their parent's surroundings other than coordinates, so having geometry "outside" the roots is okay.

I have seen artists set up sessions with random geometry outside a root object to:
- Have a place to put things that they might want to use later, e.g. library elements they want to mess with, or unfinished work.
- "Stage" their model in some kind of surrounding for visualization.
So...quite possibly even legit reasons to have a non-root mesh above a root.

**Comment by tngreene** [comment]
In 2.49, root objects can only be empty. We're saved some work!
