### ISSUE TITLE
Is it really necissary to click Add/Update Dataref Keyframe every time you update the value?

### ISSUE THREAD

**Issue by tngreene** [der-On/XPlane2Blender#287]
This seems like a pain - when you change the value of a Transform Dataref Animation, you have to click Add/Update Dataref Keyframe before switching frames or it will be lost. Why can't that be done automatically?

**Comment by tngreene** [comment]
Better solution: make it match Blender's Auto-Record behavior

**Comment by danklaue** [comment]
Indeed. In Blender, there's an option to auto-key animations. It's in the "Timeline" window... but I don't use it much, because it automatically keyframes location, rotation, and size, whereas we only ever use location and rotation, and often times, location is best not touched.  Too bad Blender doesn't let you isolate only the data set you create an initial keyframe for.... or maybe I just don't know how to do that.

**Comment by tngreene** [comment]
This seems like a bad messy idea that will just confused people. Closed.
