### ISSUE TITLE
Import OBJ "No LOAD"

### ISSUE THREAD

**Issue by SithX** [der-On/XPlane2Blender#304]
I installed the plugin "io_xplane2blender_3_4_0_b4" in Blender "2.79" but only appears in the Export menu the option of Export XPLANE but in the window of Import does not appear to me.
I'm new to Blender, and I like to edit xplane objects.

**Comment by arb65912** [comment]
Importer is not implemented.

**Comment by SithX** [comment]
And what can I do to start working?

**Comment by tngreene** [comment]
Sorry to be misleading. This was a decision that happened many years ago and we've been fielding this question ever since.

There are some answers to this on the x-plane.org forums: I've never tested them and don't support them, but it could be worth a try.

- A new addon project, [Blender Importer 1.0.1](https://forums.x-plane.org/index.php?/files/file/38643-blender-importer/)
- Go through multiple programs: Import with [XPlane2Sketchup](https://forums.x-plane.org/index.php?/files/file/1619-sketchup2xplane-x-plane-plugin-for-sketchup/), Export with Sketchup->Wavefront Obj, Import with Blender's Wavefront Obj importer. See [here](https://forums.x-plane.org/index.php?/forums/topic/105239-a-way-to-get-objs-into-blender-test-succeeded/&tab=comments#comment-1038413) and the [Youtube video](https://www.youtube.com/watch?v=BFpokxvDse0)
- Use the old [Blender 2.49 script](https://forums.x-plane.org/index.php?/files/file/31-xplane2blender-scenery-cockpit-importexport-scripts-for-blender-24/), import the .obj, save the .blend file, open it in Blender 2.78

**Keep in mind, every new importer, exporter, and program you run the .obj data through is another opportunity to lose data (such as new features not supported in those versions), corrupt data, create nonsense data, etc.** Expect some cleanup and redoing work after this.

In addition, know that some planes have copyrights and license agreements, so, don't take someone else's plane, make some changes to it, and release it as your own without checking that first. (Just messing around on your own computer with it is completely fine.)

If you do end up successfully completing one of these processes, **please** e-mail me how you did it and the files before, during, and after! You'd be helping out the development of the exporter greatly by enhancing our understanding of what sort of data we expect users to have coming into it.

We need to be robust enough to handle edge cases we've never thought of. We think along the lines of "We're garunteed that Blender could never produce a model with X data!", but don't know if XPlane2Sketchup->Wavefront->XPlane2Blender breaks such guarantees, and its too esoteric for me to spend what time I have on it.

Hope this helps,
Ted

**Comment by tngreene** [comment]
In addition, if you'd like to start learning XPlane2Blender, checkout the new [README.md](https://github.com/der-On/XPlane2Blender/tree/v3-4/README.md) file's section on documentation sources, especially Dan's video series and (www.x-plane.org) resources.
