### ISSUE TITLE
Propeller animation

### ISSUE THREAD

**Issue by Hueyman540** [der-On/XPlane2Blender#365]
Hi there,

I already succeeded to do this once or twice ... But can't really remember exactly how, it was after many trials.

I wanted to install my own prop on an X-Plane A/C. So I opened the .obj under AC3D, deleted the prop mesh, then in X-Plane 2.79 and XPlane2Blender, I animated mine without bones first and then with.

Using two frames, 1 is 0 and  2 is one. I applied rotation keyframe, then used 

- **sim/flightmodel/engine/POINT_prop_ang_deg**   for the whole prop to spin with engine

- **sim/flightmodel2/engines/prop_pitch_deg**   for each blade to rotate around it's axis for pitch change

When exporting, the prop doesn't spins. With a different dataref, it would turns very slowly according to actual RPM, but would never do a full revolution.

I'm not sure : 

- How to do it properly
- Whether I have to use bones or not
- How to deal with composite orientation ( for instance, when prop at frame two, not straight, I have to turn blade around its local axis or it's offset ... )
- Which dataref to use
- How to deal with multiple props ( my target Aircraft is a four engined Prop airliner ). I knew there were something with [0,1,2...] at the end of the dataref but last time I did it must be in 2013 or something.

Your help would be much appreciated !

Thank you

**Comment by tngreene** [comment]
Thanks submitting this bug!

Although your description was very detailed, I'm having a hard time visualizing this object. Would you be willing to make a .blend file with just the prop in it with the animations you're trying to make?

You could attach it here or e-mail it to me privately.

**Comment by Hueyman540** [comment]
Hello dude !

Thanks for your support.

Here is the .Blend

http://pasteall.org/blend/index.php?id=49996

Let me know,

Valentin


________________________________
De : tngreene <notifications@github.com>
Envoyé : mardi 24 juillet 2018 17:54:30
À : der-On/XPlane2Blender
Cc : Hueyman540; Author
Objet : Re: [der-On/XPlane2Blender] Propeller animation (#365)


Thanks submitting this bug!

Although your description was very detailed, I'm having a hard time visualizing this object. Would you be willing to make a .blend file with just the prop in it with the animations you're trying to make?

You could attach it here or e-mail it to me privately.

**Comment by tngreene** [comment]
Now for the tougher part. Regretably this is not well documented, but, if you look at the README you can see an example of a whole Microjet someone made.

XPlane2Blender requires Blender Keyframes and Dataref Keyframes for each Blender Mesh (or Light or Empty) or Blender Pose Bone you want to animate. It pairs those together, *per object* and produces the animation table. *Per object* is important because it is not per object and whatever its children are.

I see your ``Armature`` has Blender Keyframes and Dataref Keyframes for the dataref ``sim/flightmodel/engine/POINT_prop_ang_deg``. Although I'm not sure the use of POINT_prop_ang_deg (you really could be right to use there! I'm a bit confused as to how this is trying to work is all), it will animate.

Its *child ``Hub``, however, only has the dataref ``sim/flightmodel2/engines/prop_no_disc_rotation_angle_deg``. Only the dataref, no keyframes of any kind. And no index for that dataref. All of the Blades are similarly lacking in keyframes.

**Comment by Hueyman540** [comment]
Hello dude,


Thank you ! Yeah it's large, it has no impact on frame rate with current optimiosed engine, even though I know it could be optimised ( but for no valid reasons ). I did the Hamitlon Standard 24E60 Hub in a CNC

________________________________
De : tngreene <notifications@github.com>
Envoyé : mercredi 25 juillet 2018 00:27:00
À : der-On/XPlane2Blender
Cc : Hueyman540; Author
Objet : Re: [der-On/XPlane2Blender] Propeller animation (#365)


Alright, I have some feedback. Firstly, great looking Propeller! Super cool! Secondly, there are a few categories of problems here. So, here is some easy stuff.

  *   As for things rotating very slowly, Your animated armature turns at 1 degree every 1.0 of POINT_ang_deg. That is a very small change in either degrees, value changed, or both.

  *   The export is very very very large! Consider simplifying your geometry and merging some faces together. Particularly the Hub object. @alxunru<https://github.com/alxunru> says that it is good enough for a CNC machine, which is unnecessarily detailed for X-Plane's purposes. It will definitely speed up export.

  *   You are probably using the right datarefs, but you haven't put in the index in the textbox. For instance, sim/flightmodel2/engines/prop_pitch_deg should be used as
sim/flightmodel2/engines/prop_pitch_deg[0],sim/flightmodel2/engines/prop_pitch_deg[1],etc. The brackets and number go right in the dataref path. 0 means "The first" (because programming culture and some math stuff).

**Comment by Hueyman540** [comment]
Hello dude,


Thank you ! Yeah it's large, it has no impact on frame rate with current optimiosed engine, even though I know it could be optimised ( but for no valid reasons ). I did the Hamitlon Standard 24E60 Hub in a CNC program that's why !


Okay, I'll take a look at this, thank you very much for your input.


Valentin


________________________________
De : tngreene <notifications@github.com>
Envoyé : mercredi 25 juillet 2018 00:41:27
À : der-On/XPlane2Blender
Cc : Hueyman540; Author
Objet : Re: [der-On/XPlane2Blender] Propeller animation (#365)


Now for the tougher part. Regretably this is not well documented, but, if you look at the README you can see an example of a whole Microjet someone made.

XPlane2Blender requires Blender Keyframes and Dataref Keyframes for each Blender Mesh (or Light or Empty) or Blender Pose Bone you want to animate. It pairs those together, per object and produces the animation table. Per object is important because it is not per object and whatever its children are.

I see your Armature has Blender Keyframes and Dataref Keyframes for the dataref sim/flightmodel/engine/POINT_prop_ang_deg. Although I'm not sure the use of POINT_prop_ang_deg (you really could be right to use there! I'm a bit confused as to how this is trying to work is all), it will animate.

Its *child Hub, however, only has the dataref sim/flightmodel2/engines/prop_no_disc_rotation_angle_deg. Only the dataref, no keyframes of any kind. And no index for that dataref. All of the Blades are similarly lacking in keyframes.

**Comment by tngreene** [comment]
So, were you able to fix this and get the animation you wanted?

**Comment by tngreene** [comment]
If you could post another .blend file like you did before, or e-mail it to me, I'd be glad to take a look! I'm guessing its some small thing in the wrong place, because it sounds like you've got a very good idea of what it should look like in the end, however it could be a bug! You never know where they're going to show up unless you really confirm its just an authoring issue.

So, this is indeed important to investigate: not just for helping out our users but also for the product itself!

**Comment by Hueyman540** [comment]
Hi dude,

Yeah, for sure, please take a look http://pasteall.org/blend/index.php?id=50130

Valentin

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10


De : tngreene <notifications@github.com>
Envoyé : Saturday, August 11, 2018 4:03:36 PM
À : der-On/XPlane2Blender
Cc : Hueyman540; Author
Objet : Re: [der-On/XPlane2Blender] Propeller animation (#365)


If you could post another .blend file like you did before, or e-mail it to me, I'd be glad to take a look! I'm guessing its some small thing in the wrong place, because it sounds like you've got a very good idea of what it should look like in the end, however it could be a bug! You never know where they're going to show up unless you really confirm its just an authoring issue.

So, this is indeed important to investigate: not just for helping out our users but also for the product itself!

**Comment by tngreene** [comment]
I just wanted to say that this hasn't been forgotten! I'm currently asking some of our artists to look at it when they are able to. Hopefully that will be soon.

**Comment by tngreene** [comment]
Okay, so, I think know what the problem is! I don't think  D9511F.000 and  D9511F.003 are properly animated - they are rotating around the same axis as the hub. You can see this more easily if you mute the Hub's animation (open the Dope Sheet and click the [Mute button](https://docs.blender.org/manual/en/dev/editors/graph_editor/channels.html?highlight=mute) next to Hub's Rotation channel.).

What I am guessing you did was you made 1 blade, stuck straight up, copied it 3 times, rotating them in place, then attempted to animating the by 1 degree for all of them.

Look at D9511F.000 from the side and D9511F.002 from the top very closely. You'll see D9511F.000/003 rocks up and down, not twisting back and forth! .001/.002 can simply be rotated by 1 degree around the Z-Axis because the blade was modeled up and down it and it will look right.

Euler XYZ rotation mode works by rotating x degrees along the X axis, then y degrees along the Y axis, then z degrees along the Z axis.

To have the .000/.003 blade's vertices be modeled as straight up and down, but be shown as on the side and twisting would require more than your 90 and 91 degrees of rotation along the Y axis. Play around with the rotation tool and see at the values Blender comes up with. Yikes! In addition, you have also have a performance decrease! To always have to rotate the vertices of the blade into position,  then rotate to twist them (in reality it would be quiet complex to make it look right, not something you'd want to figure out by hand) is a waste of time.

Two solutions:
1. Edit the mesh for .000/.003 (or do it once and copy and paste it), select everything and prerotate it into position in edit mode. Now you truely can rotate one degree along one axis, just like .001/.002! You'll also reduce the amount of animations needed. Pro Tip: Moving the vertices so the base of the blade is at the origin may help in positioning them. That's just a tip.

2. Keep the meshes where they are and use Axis Angle instead of Euler XYZ. Use the Rotate tool to set the degrees of rotation, and Blender will figure out that special axis that makes it all work. XPlane2Blender figures it out too, but it won't be as optimized.

See if that helps!

**Comment by tngreene** [comment]
(Also, as a quick rule, make the most simple rotation as possible. A rotation of 0,91,0 is effectively the same as 90,91,90. The simpler animation is easier to debug and performs better.)

**Comment by Hueyman540** [comment]
I succeed to do it properly before on other prop/planes but it seems more of a luck than a working method..


Maybe you can edit the .blend to show the exact stuff that needs to be done, or show a simple example with basic meshes ?


Thanks,

Valentin

________________________________
De : tngreene <notifications@github.com>
Envoyé : jeudi 16 août 2018 19:42:54
À : der-On/XPlane2Blender
Cc : Hueyman540; Author
Objet : Re: [der-On/XPlane2Blender] Propeller animation (#365)


(Also, as a quick rule, make the most simple rotation as possible. A rotation of 0,91,0 is effectively the same as 90,91,90. The simpler animation is easier to debug and performs better.)

**Comment by tngreene** [comment]
[example_of_solutions.zip](https://github.com/der-On/XPlane2Blender/files/2297353/example_of_solutions.zip)

This contains 4 "blades", simple twisted cubes. The original shape which was copied and pasted, a copy of .000, and an example of my 2 solutions. Its not the most clean and precise, but it illustrates the principles.

**Comment by tngreene** [comment]
If you still need help, please re-open this or e-mail me. I hope your animation is going well!
