### ISSUE TITLE
2.49: Set LOD based on layers-based export

### ISSUE THREAD

**Issue by tngreene** [der-On/XPlane2Blender#382]
2.49 uses layers to categorize LOD buckets. We'll need to copy that into the LOD settings of XPlane2Blender

**Comment by airfightergr** [comment]
I think this kind of old thinking and should be implemented another ways. 

Back in those days, scenery objects were rarely complex. Nowadays objects are much complex and require to be broken down in multiple layers due to the limit of 1 texture per object. Big terminals can easily require up to 5 layers (if not even more). And because you want all in one file for modelling, baking etc, it will be very difficult later to break them down, which also removes the ability to go back and redo or fix any issues.

My proposition is to have (in objects tab?) a selection in which LOD each mesh will belong to. Each LOD properties should be set in the export settings.

**Comment by tngreene** [comment]
I agree this is old thinking but, the point of the converter is to take the old projects and make them work in the new version with as little changes as possible, and hopefully all in one step that the user doesn't even have to initiate.

The hope is that people will be able to open it and feel right at home.

**Comment by lehthanis** [comment]
@tngreene  This may not be a good place to put this question, but I was actually wondering now how do we actually do LODs in 3.5?  I see in root object I can select the number of LOD's and set their distances, but how do I determine which geometry is LOD1 and which geometry is LOD2, etc?  Am I missing something?

**Comment by tngreene** [comment]
See also the comment on #410, https://github.com/der-On/XPlane2Blender/issues/410#issuecomment-462975493
