### ISSUE TITLE
ATTR_cockpit not resetting for each TRIS that needs it (3.5.0-Beta 2)

### ISSUE THREAD

**Issue by crzydmnd12** [der-On/XPlane2Blender#385]
Exporting with Beta 2, I noticed some of my cockpit panels were no longer capturing mouse coordinates in the click_3d_x_pixels and click_3d_y_pixels datarefs.  At some point an ATTR_no_cockpit occurs in the list of TRIS for the cockpit panels but and the TRIS that need ATTR_cockpit don't get reset with a new pair of ATTR_cockpit/ATTR_no_cockpit statements.  Falling back to Beta 1, the obj exports with all the necessary ATTR_cockpit and ATTR_no_cockpit pairs and mouse coordinates work again in all the cockpit panels.

**Comment by tngreene** [comment]
We have some good ideas what caused it, but having a simplified version of your .blend file would be very very helpful. For instance, a copy with only the .obj you're having trouble with and its related data. If you're worried about exposing your work, you can e-mail it to me and it will be deleted when the bug is closed. It would never be shared with anyone outside of Laminar Research.

**Comment by tngreene** [comment]
So, I've tried making a file to replicate this, and I definitely have something which exhibits an expected behavior - repetitive ATTR_cockpit/ATTR_no_cockpit pairs are optimized away, but that isn't what you're facing.

I believe that there could be a problem, but I really need a test file from you. You can e-mail it to me at ted AT x-plane.com, or upload a zip file here (prefered) or use a variety of online file sharing services.

**Comment by tngreene** [comment]
I made a .blend file with 3 cubes, alternating having a cockpit and no cockpit materials. Using weights I made them export in the intended order and didn't find the issue you've talked about, with beta.3 code.

```
# 0 ROOT
# 1 Mesh: 01_Cube_ckpt
# MESH: 01_Cube_ckpt	weight: 0
# MATERIAL: cockpit panel
ATTR_cockpit
TRIS	0 36
# 1 Mesh: 02_Cube
# MESH: 02_Cube	weight: 1
# MATERIAL: Material
ATTR_shiny_rat	0.5
ATTR_no_cockpit
TRIS	36 36
# 1 Mesh: 03_Cube_ckpt
# MESH: 03_Cube_ckpt	weight: 2
# MATERIAL: cockpit panel
ATTR_cockpit
TRIS	72 36

# Build with Blender 2.78 (sub 0) (build b'e92f235283'). Exported with XPlane2Blender 3.5.0-dev.0+39.NO_BUILD_NUMBR
```

To look into this more I'll definitely need a .blend file from you, or you can tell me if the attached doesn't match your problem.

[attr_cockpit_problem.zip](https://github.com/der-On/XPlane2Blender/files/2446902/attr_cockpit_problem.zip)
