### ISSUE TITLE
Feature Request? Output list of manipulators/commands/datarefs

### ISSUE THREAD

**Issue by lehthanis** [der-On/XPlane2Blender#394]
I've often thought about making an obj parser that would go through and create a csv file of all the manipulators and their associated commands and datarefs and maybe even their values...I may still do that, but would this be a useful feature to add to the exporter? I end up having to keep track of so many different custom datarefs and commands and it would just be super nice to have a list that I could always refer to automatically generated. Thoughts?

**Comment by tngreene** [comment]
I'm glad you didn't go for making an OBJ Parser!!! Feature requests like "Can XPlane2Blender make a report that says..." generally don't get filled because
1. Everyone has their own needs and format they want. You can't make it for a lot of people
2. It is so easy to access this stuff anyway using Blender's API. I make "collect all data from some stuff and print it out) all the time as part of debugging the addon. Attached is a report maker that prints dataref information, command information, and manipulator information for all the non-empties in a file.

Run the text block called Report Maker (which can be copied, saved, and re-used. I place it in the public domain.) It'll generate "Data Report". I've also tried to annotate the script so you can compare with XPlane2Blender's source code and see where names and values come from.

If you have enough programming knowledge or access to parse an OBJ (not as easy as you might think!) you can definitely learn how to do this.

Its also extremely useful, not just to print things out but to do stuff like rename every object, move things between layers very intelligently, change values, and more. This type of automation can save you hours of clicking. I highly recommend it. You only need an intro to Python course, and I have a vested interest in making more XPlane2Blender users who Python programmers!

[data_reporter_example.zip](https://github.com/der-On/XPlane2Blender/files/2484237/data_reporter_example.zip)

This is a portion of the report from running this on the BD-5J Microjet. Tell me if the script won't work on one of your projects and if you'd like more resources on scripting Blender.

- [Getting Started](https://docs.blender.org/api/blender_python_api_current/info_quickstart.html)

```
NAV_DME_Power:
    Dataref Path: none, Type: transform, Value: 0.0, Loop: 0.0
    Dataref Path: sim/cockpit2/radios/actuators/nav1_power, Type: hide: Value 1: 0.0, Value 2:0.0
    Dataref Path: sim/cockpit2/switches/avionics_power_on, Type: hide: Value 1: 0.0, Value 2:0.0
    Dataref Path: sim/cockpit2/electrical/bus_volts[0], Type: hide: Value 1: 0.0, Value 2:0.0
    Dataref Path: sim/operation/failures/rel_navcom1, Type: hide: Value 1: 6.0, Value 2:6.0
    Dataref Path: sim/operation/failures/rel_nav1, Type: hide: Value 1: 6.0, Value 2:6.0
NAV_Flip_Freq_Btn:
NAV_Flip_Freq_Btn_Manip:
    Dataref 1:sim/cockpit2/radios/actuators/nav1_right_is_selected
    On Value:0.0
    Off Value:1.0
    Wheel Delta:0.0
NAV_Freq_000.00_:
NAV_Freq_000.01_:
    Dataref Path: sim/cockpit2/radios/actuators/nav1_frequency_khz, Type: transform, Value: 9.0, Loop: 10.0
NAV_Freq_000.10_:
    Dataref Path: sim/cockpit2/radios/actuators/nav1_frequency_khz, Type: transform, Value: 99.0, Loop: 100.0
NAV_Freq_001.00_:
    Dataref Path: sim/cockpit2/radios/actuators/nav1_frequency_Mhz, Type: transform, Value: 9.0, Loop: 10.0
NAV_Freq_010.00_:
    Dataref Path: sim/cockpit2/radios/actuators/nav1_frequency_Mhz, Type: transform, Value: 99.0, Loop: 100.0
NAV_Freq_100.00_:
    Dataref Path: sim/cockpit2/radios/actuators/nav1_frequency_Mhz, Type: transform, Value: 999.0, Loop: 1000.0
NAV_Large_Tuner_Knob:
    Dataref Path: sim/cockpit2/radios/actuators/nav1_standby_frequency_Mhz, Type: transform, Value: 136.0, Loop: 0.0
NAV_Large_Tuner_Knob_Manip:
    Dataref 1:sim/cockpit2/radios/actuators/nav1_standby_frequency_Mhz
    Drag X:0.125
    Drag Y:0.0
    Drag Z:0.0
    Value 1:108.0
    Value 2:117.94999694824219
    Wheel Delta:0.0
```
