### ISSUE TITLE
Text substitution in dataref paths

### ISSUE THREAD

**Issue by dpospisil** [der-On/XPlane2Blender#398]
It would be very useful if the exporter could do some sort of text substitution in dataref paths.

The use case is multiple objects in scene with the same animations which are required to animate individually. Currently, one needs to manually override dataref names in every object.

If there is a way to include object name or other blender properties in the dataref path, that would be awesome.

**Comment by tngreene** [comment]
I think a Python script could solve this easily instead of adding to the XPlane2Blender code base. Make a text block and write a script that looks like this:

```python
# bpy is the module that contains all code related to the Blender data model
import bpy

# Make a list of objects you want to alter.
# You could also change it to all the objects currently selected,
# or get every object with part of a certain name,
# or every object that has some certain piece of data.
# This is programming, do what you want!
# 
# You'll see that Cube is untouched because it isn't in the list
objs_with_same_dataref = [
    bpy.data.objects["WingL"], 
    bpy.data.objects["WingR"],
    bpy.data.objects["SomethingElse"]
]

# The dataref you want to apply to every one of those objects
# Try uncommenting only one of the following to rewrite the datarefs
#dataref_for_all = "sim/graphics/animation/sin_wave_2"
dataref_for_all = "third/party/ref"
#dataref_for_all = ""

# Iterate through every object and change them
for ob in objs_with_same_dataref:
    # Selecting which dataref in the list of datarefs
    # might be tough, but you can figure it out
    # For now I'll just assume that each of these has one dataref
    #
    # See what happens if you include "Cube" in your list!
    ob.xplane.datarefs[0].path = dataref_for_all
```

If you run this, every object in your list of objects to alter will have the same new dataref path. No special parenting needed. Since the path is just a string, whatever you want or need it to be is easy.

Python programming is very easy and this sort of stuff where you access the Blender data model and change parts of it is also very easy. It is a great productivity booster! Are you very familiar with it?

**Comment by tngreene** [comment]
I'm closing this issue because it is a feature that won't be added, but please feel free to make more comments or e-mail me about the example I posted.
