### ISSUE TITLE
ATTR_light_level only lighting certain parts of OBJ

### ISSUE THREAD

**Issue by bobcat6** [der-On/XPlane2Blender#417]
Somehow, on my Windows 10 system with Blender 2.79, xplane2blender 3.5.0-rc.1 and X-Plane 11.31, most parts of a cockpit object do not light up or respond to their ATTR_light_level assignment.

The weirdest thing: the exact same .blend file on my Mac, with a slightly older version of xplane2blender and running X-Plane 10 (whatever the final version of X-Plane 10 was) exports the cockpit .obj fine; all of the lit items appear and respond to the various ATTR_light_level dataref values.

For clarity's sake, I know how to set up the materials and designate light level override and enter the dataref that I want to manipulate the light level of that particular group of similarly-materialed mesh objects.  This works on my Mac; exporting the .obj from the exact same .blend file and opening the aircraft in X-Plane 10, everything works fine.  On my Windows system only a few (very few) parts of the cockpit.obj respond to their respective ATTR_light_level dataref.  There is only one material (ATTR_light_level) that works and there are parts/meshes that use that very same material yet do not work.  So it's not a matter of the other materials having a misspelled dataref path or something, there is inconsistent success/failure within the same material that does work.

Inspecting the .obj file, I do see the light levels being called for and everything seems to be spelled correctly.  I do not understand the OBJ language well enough to understand what TRIS and the seemingly arbitrary numbers that follow mean (obviously this attribute is being assigned to certain triangles/faces of geometry but I don't understand how those numbers correspond to the disparate parts that share this attribute).  The syntax seems correct in all the ways that I do understand though.

Everything else seems fine.  The animation, tool tips, albedo textures, etc. are all fine.  The LIT textures just don't appear when they should.  I even monitor the dataref values that the LIT textures are supposed to respond to; the values change as expected (e.g. transition from 0 to 1) but no lighting change happens on the surface of the object (except for on 4 parts, out of about 50).  All of the lit textures on the exterior model (e.g. the landing light bulbs) function properly and respond to ATTR_light_level.  The problem seems confined to the cockpit.obj.

A test that I will try next is to export the cockpit.obj on my Mac and bring that obj (exported for v 10.3) over to my Windows/X-Plane 11 machine and see if the light levels respond.

**Comment by bobcat6** [comment]
Further testing suggests that this has to be a bug in X-Plane 11.  The very same cockpit.obj (copied to both machines) works in X-Plane 10 and does not work in X-Plane 11.

**Comment by tngreene** [comment]
Thank you for your detailed bug report and investigation! Be sure to file a bug on the main product's [bug base](https://dev.x-plane.com/support/bugreport.html).

**Comment by tngreene** [comment]
Also for TRIS: Try experimenting with this. Delete everything, make two planes primitives and rotate them 90 degrees (in edit mode) so they're along the X-Z plane (because this is actually X-Plane's X-Y). Select one and dissolve one vertex, turning it into a flat triangle. Snap your primitives to nice grid lines so their co-ordinates are nice and easy to interpret. Make sure they're not touching. Turn on `Optimize` and `Print Debug Info` (to see what is going on easier), give them any Material and Export.

```
I
800
OBJ

POINT_COUNTS	7	0	0	9

VT	2	4	-0	-0	-0	1	0	0	# 0, Triangle
VT	4	2	-0	-0	-0	1	0	0	# 1, Triangle
VT	2	2	-0	-0	-0	1	0	0	# 2, Triangle
VT	-5	-6	-0	0	-0	1	0	0	# 3, Square
VT	-5	-8	-0	0	-0	1	0	0	# 4, Square
VT	-7	-8	-0	0	-0	1	0	0	# 5, Square
VT	-7	-6	-0	0	-0	1	0	0	# 6, Square

# Triangle
IDX	0
IDX	1
IDX	2
# Square, part 1
IDX	3
IDX	4
IDX	5
# Square, part 2 (A square can be broken down into two triangles)
IDX	5
IDX	6
IDX	3

# 0 ROOT
# 1 Mesh: Square
# MESH: Square	weight: 1
# MATERIAL: Material
ATTR_shiny_rat	0.5
TRIS	3 6
# 1 Mesh: Triangle
# MESH: Plane	weight: 3
# MATERIAL: Material
TRIS	0 3

# Build with Blender 2.78 (sub 0) (build b'e92f235283'). Exported with XPlane2Blender 3.5.0-dev.0+45.NO_BUILD_NUMBR
```

## Breakdown

### POINT_COUNTS
A square has 4 vertices, a triangle has 3, so we have 7 vertices in the vertex table.

You can see at the top the POINT_COUNTS describing the content of vertex table and other tables
> POINT_COUNTS <tris> <lines> <lites> <indices>
> 
>This defines the size of the data tables. Four integer numbers define the number of entries in each table.

### VT Table
By reading the VT table, you can quite clearly see your Triangle and Square.

```
VT	2	4	-0	-0	-0	1	0	0	# 0, Triangle
VT	4	2	-0	-0	-0	1	0	0	# 1, Triangle
VT	2	2	-0	-0	-0	1	0	0	# 2, Triangle
```

### IDX Table
As each face is turned into triangles, those are written into the IDX table. `IDX 0`, `IDX 1`, `IDX 2` are referring to the first, second, and third entry in the VT table. These turn the Vertex Soup into something with meaning. IDX10 is simply IDX 10 at a time (for faster loading in X-Plane).

### TRIS
Later in the commands section. We finally get to TRIS

> TRIS <offset> <count>
> This command draws count/3 triangles based on the vertices referenced by the indices starting at ‘offset’ in the index table and running consecutively upward. (In otherwords, the indices must be adjacent, but they can refer to non-adjacent vertices). Count must be a multiple of 3. Vertices come from the triangle table.

So, for Square, it's geometry is drawn with `TRIS 3 6`. So, go to the IDX table, and find index 3 (the 4th entry because the table starts at index 0). X-Plane starts here and draws the next 6 vertices referenced. TRIS references the index table which references the vertex table!

## Why?
By having each TRIS reference the IDX table, and the IDX table reference the VT table, we can keep the OBJ more human readable, faster to load and optimize in X-Plane, and allows for neat tricks when (and hopefully no one has to do this anymore) hand debugging an OBJ. A TRIS statement can be re-ordered and commented just by moving and commenting out that one line. Can you imagine if you had little mini-VT tables everywhere? It'd be a mess. If you were to change the weight or names of the Square and Triangle so they exported in a different order, all that changes is the order of TRIS calls. Much easier to look at.

Does that help clarify what TRIS is doing and what it changes?

I've attached the .blend file I used to make this.

[TRIS_demo.zip](https://github.com/der-On/XPlane2Blender/files/2870079/TRIS_demo.zip)
