### ISSUE TITLE
Copy X-plane Custom Properties to bones, meshes, etc.

### ISSUE THREAD

**Issue by danklaue** [der-On/XPlane2Blender#82]
There IS a script in Blender to copy features, but X-Plane custom properties aren't included.  Some implementation of this would be lovely.  E.g. copying ATTR_no_blend to all selected objects in Blender.

**Comment by tngreene** [comment]
By using Blender's "Duplicate" feature, custom properties are copied as of now. Is this what was meant by "copied"?

**Comment by danklaue** [comment]
I mean, when you hit "ctrl+C" in Blender, you get this:
<img width="189" alt="screen shot 2017-07-19 at 10 33 51 am" src="https://user-images.githubusercontent.com/359923/28375802-1b395970-6c6e-11e7-8682-4ad4ad1d73f9.png">

The "X-Plane" category does not show up in there.  It'd be great to be able to copy X-Plane attributes, such as manipulator data or show/hide logic to other components that are not a duplicate of the original object.

**Comment by tngreene** [comment]
This is from an [addon](https://wiki.blender.org/index.php/Extensions:2.6/Py/Scripts/3D_interaction/Copy_Attributes_Menu) called "Copy Attributes Menu", right?

Or was this added to Blender itself as a feature?

Looking through the addon's source code, it looks like it takes operations from a very specific source and would require modifier *that addon*, instead of XPlane2Blender (which we can't do). If this has become a built-in Blender feature, please tell me how to find it so I can investigate.

**Comment by danklaue** [comment]
It looks like it's one of the add-ons included in Blender by default, but you have to enable it in the user preferences. (It's off by default). It's called "3D View: Copy Attributes Menu"

**Comment by tngreene** [comment]
It appears that Blender has this functionality in it via "Copy to Selected". It works with any property. I tried copying Manipulator type across several cubes and it worked!

[How do I copy a property from an active object to selected objects?](https://blender.stackexchange.com/questions/1177/how-do-i-copy-a-property-from-an-active-object-to-selected-objects)
