### ISSUE TITLE
Drag Axis Manipulators not exporting properly

### ISSUE THREAD

**Issue by Aubrey8** [der-On/XPlane2Blender#85]
I'm using Blender 2.61 and the latest 3.20 script version.

I've been trying to export drag axis manipulators with varied results. It's a standard cockpit rotary knob that should rotate a total of 260 degrees in 3 keyframes to control instrument brightness. I've set up all the animation keyframes and x-plane animation keyframes and set the datarefs as per the excellent 'New Changes' video but when I export, the behaviour in X-Plane is very erratic. On examining the obj text file, the wrong rotational information has been exported, so when the keyframes should read as follows: Keyframe 0: 0, 1: 130, 2: 260 they read something like: Keyframe 0: 0, 1: 100.12354, 2: -67.84938.

I can't see any pattern to this and every correcting the data in the obj file does not help. I'm also having difficulties setting a particular object (glass screen) to display the 2D clickable panel texture, despite selecting all of the relevant 2D panel options.

I'd be grateful if you could suggest some ways forward, if you'd like to have a look at the blend file then let me know: aubreydawson@me.com

Also, are you accepting donations for the work on the script?

Thanks

Aubrey

**Comment by tngreene** [comment]
6 years later the problem with animation seems to be fixed. Closing the bug because the rest of it is vague and has been inactive for almost 6 years. If there really is still a problem with the panel texture we should make a new bug for it with more detail.

[85_blender_tets.zip](https://github.com/der-On/XPlane2Blender/files/1668278/85_blender_tets.zip)
